/*
 * Budget Rest APIs
 * This page lists all the rest apis for Hotel Management App.
 *
 * OpenAPI spec version: 1.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.uhe.app.client.api;

import com.uhe.app.client.model.MonthlyModel;
import com.uhe.app.client.model.Payment;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for BudgetControllerApi
 */
@Ignore
public class BudgetControllerApiTest {

    private final BudgetControllerApi api = new BudgetControllerApi();

    
    /**
     * Einzahlung/Auszahlung
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addPaymentUsingPOSTTest() {
        Payment payment = null;
        Payment response = api.addPaymentUsingPOST(payment);

        // TODO: test validations
    }
    
    /**
     * Statusabfrage
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void askForStatUsingGETTest() {
        Integer month = null;
        Integer year = null;
        MonthlyModel response = api.askForStatUsingGET(month, year);

        // TODO: test validations
    }
    
}
